---
db:
  host: "db"
  user: "postgres"
  password: "sprinkler"
  dbname: "postgres"
  sslmode: "disable"

orchard:
  address: ":8082"

control:
  address: ":8080"
  trustedProxies:
    - "0.0.0.0/0"
    - "::/0"
  apiKey: "changeme"

scheduler:
  interval: "1s"
  orchardAddress: "http://ws:8082"
...
